# -*- coding: utf-8 -*-
"""Copy of homework-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1915sa-f-2rlIAdHfMnsc4TgKNmy8ZnMk

# Homework 1: Introduction to Jupyter and GitHub

**Due Friday, April 10.**

Cade Goodrich

### Homework checklist

Before submitting, make sure that you

- Fill in your name in the space above ///(done)///
- Cite any resources that you used while working on this homework
- 4. Insert and fill in a new markdown cell
- 5. Insert and fill in a new code cell

## Introduction

Now that you have **Python 3** and **Jupyter** installed, you can open this notebook in Jupyter. How you do this might vary a bit from system to system, but a common approach is to run `jupyter notebook` from the command line (a.k.a. terminal) in the folder where you've downloaded this file (`homework-1.ipynb`). 

We won't be running anything else directly from the terminal in this course, but more information is available [here](https://swcarpentry.github.io/shell-novice/) if you're interested.

## 4. Practice basic Jupyter I

You may have noticed that the text in this document is organized into discrete blocks called cells. You can click on any cell to select it, and double click to edit. Edit the first cell to enter your name. Once you're done, you can execute the code (or format the text) in the cell by using the menu bar above, or with the keyboard shortcut `shift + enter`.

Jupyter notebooks use a lightweight language called [Markdown](https://en.wikipedia.org/wiki/Markdown) for formatting plain text. Here is a [guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) to some common Markdown notation. You can also use Markdown to format equations by enclosing them in `$` symbols! Equation formatting follows $\LaTeX$ conventions.

Let's practice using Jupyter and Markdown by:  
1. Inserting a new cell below this one. To do this, select this cell and select `Insert` > `Insert Cell Below` from the menu.  
2. Click on the new cell and change its type to Markdown by selecting it and selecting `Cell` > `Cell Type` > `Markdown` from the menu.  
3. Add a heading in that cell with a single `#`, and a subheading with `##`.  
4. Now add a numbered list below that. You can also generated un-numbered lists by using `*` or other starting characters.  
5. Add an equation to your text box using Latex.

# Mark down cell is a cell using text i hope!
##hope this is right
1. test 
2. test1
*unnumbered*

*unnumbered1*

$math+computers=confusion$

## 5. Practice basic Jupyter II

Let's now do some light practice with code cells in Jupyter:
1. Insert another cell below this one. By default, it will be a code cell.  
2. Define a variable in that cell. For example, we could set `x = 3`.
3. Now let's insert another new cell below that one. Print out the variable that you defined in the previous cell. For the example above, I could write `print(x)`.  

Note that, as shown above, variables defined in one cell still hold their values in another cell! Each cell is not a separate compute environment. **Variables are shared across the entire notebook.** This is important to keep in mind when you are coding, so that you don't accidentally use a variable that you might not have intended to use.
"""

x=4

print(x)

"""## 6. Submit the homework assignment

First, save your modified version of this file by using the shortcut `contrl+s` or by selecting `File` > `Save and Checkpoint` from the menu. Next, upload it to your GitHub repository for this homework.
"""